version: '3'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=udash
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=udash
    ports:
      - 5432:5432
